version: '2.1'
services:
  dev:
    build:
      context: .
      args:
        - username=${DEVUSER:-defaultuser}
        - publickey=${PUBLIC_KEY}
    ports:
      - "44422:22"  # SSH port
      - "36000-36020:36000-36020"  # Open ports for development
      - "60000-60010/udp:60000-60010/udp"  # Mosh
    volumes:
      # Sibling docker containers
      - "/var/run/docker.sock:/var/run/docker.sock"

      # Shared volume between in container home folder & host home folder
      - "/home/${DEVUSER:-defaultuser}:/home/${DEVUSER:-defaultuser}"
    environment:
      - TERM=xterm-256color
    hostname: awesomeserver
