version: "3.9"
services:
  personalenv:
    build:
      context: .
      args:
        - USERID=$USERID
        - GROUPID=$GROUPID
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: $USERID:$GROUPID
    ports:
      - "4500:22"
    tty: true

